"""python12

Revision ID: c6d1e08a2591
Revises: 
Create Date: 2018-06-09 17:11:57.198411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6d1e08a2591'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('title', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
