"""python12

Revision ID: fabcf5517258
Revises: c6d1e08a2591
Create Date: 2018-06-09 17:17:21.982212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fabcf5517258'
down_revision = 'c6d1e08a2591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('title', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('qq_number', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'qq_number')
    op.drop_column('roles', 'title')
    # ### end Alembic commands ###
